services:
  - type: web
    name: pdf-chat-agent
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.enableCORS false"
    envVars:
      - key: OPENAI_API_KEY
        sync: false